name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
        
      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build
          
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ${{ env.FIREBASE_EMULATORS_PATH }}
          key:
            ${{ runner.os }}-firebase-emulators-${{
            hashFiles('emulator-cache/**') }}
        continue-on-error: true

      - name: E2E on Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: |
             yarn firebase:dev
             yarn serve:dist
          wait-on: "http://localhost:8080/"
          wait-on-timeout: 120
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # Service Account (used for creating custom auth tokens)
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
