name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ${{ env.FIREBASE_EMULATORS_PATH }}
          key:
            ${{ runner.os }}-firebase-emulators-${{
            hashFiles('emulator-cache/**') }}
        continue-on-error: true


      - name: E2E on Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          build: yarn build
          start: |
             yarn firebase:dev
          wait-on: "http://localhost:5000/"
          wait-on-timeout: 120
          spec: cypress/integration/*.spec.js

          # Specify the command that is run so that it uses the node version in the environment
          # https://github.com/cypress-io/github-action/issues/467
          command: yarn cypress run --config baseUrl=http://localhost:5000/
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROVIDENT_RI }}
