name: Cypress Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: dist
          if-no-files-found: error
          path: dist
      - run: yarn firebase:dev
      
  cypress-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: E2E on Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: yarn serve
          # quote the url to be safe against YML parsing surprises
#           wait-on: 'http://localhost:8080'
