name: Cypress Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            
      - name: Install packages
        run: yarn install
      
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: dist
          if-no-files-found: error
          path: dist
      
  cypress-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: E2E on Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: firebase emulators:exec "yarn serve"
          # quote the url to be safe against YML parsing surprises
#           wait-on: 'http://localhost:8080'
